import { NavItem } from './nav-item/nav-item';

export const navItems: NavItem[] = [
  ////////////////////////////////////////// ADMIN ROUTES //////////////////////////////////////////
  {
    navCap: 'Admin',
    roles: ['Admin'],
  },
  {
    displayName: 'Alerts',
    iconName: 'solar:bell-bing-line-duotone',
    route: '/admin/alerts',
    roles: ['Admin'],
  },
  {
    displayName: 'Areas',
    iconName: 'solar:map-point-line-duotone',
    route: '/admin/areas',
    roles: ['Admin'],
  },
  {
    displayName: 'Database Maintenance',
    iconName: 'solar:database-line-duotone',
    route: '/admin/maintenance',
    roles: ['Admin'],
  },
  {
    displayName: 'Devices',
    iconName: 'solar:devices-line-duotone',
    route: '/admin/devices',
    roles: ['Admin'],
  },
  {
    displayName: 'Incidents',
    iconName: 'solar:danger-triangle-line-duotone',
    route: '/admin/incidents',
    roles: ['Admin'],
  },
  {
    displayName: 'Maintenance',
    iconName: 'solar:settings-line-duotone',
    route: '/admin/maintenance-logs',
    roles: ['Admin'],
  },
  {
    displayName: 'Readings',
    iconName: 'solar:chart-square-line-duotone',
    route: '/admin/readings',
    roles: ['Admin'],
  },
  {
    displayName: 'Positions',
    iconName: 'solar:map-point-wave-line-duotone',
    route: '/admin/positions',
    roles: ['Admin'],
  },
  {
    displayName: 'Roles',
    iconName: 'solar:shield-user-line-duotone',
    route: '/admin/roles',
    roles: ['Admin'],
  },
  {
    displayName: 'Sensors',
    iconName: 'solar:radar-2-line-duotone',
    route: '/admin/sensors',
    roles: ['Admin'],
  },
  {
    displayName: 'Shifts',
    iconName: 'solar:clock-circle-line-duotone',
    route: '/admin/shifts',
    roles: ['Admin'],
  },
  {
    displayName: 'Users',
    iconName: 'solar:users-group-rounded-line-duotone',
    route: '/admin/users',
    roles: ['Admin'],
  },
  ////////////////////////////////////////// TEMPLATE ROUTES //////////////////////////////////////////
  {
    navCap: 'Manager',
    roles: ['Manager'],
  },
  {
    displayName: 'Dashboard',
    iconName: 'solar:widget-add-line-duotone',
    route: '/main/dashboard',
    roles: ['Manager'],
  },
  // {
  //   displayName: 'Dashboard 1',
  //   iconName: 'solar:widget-add-line-duotone',
  //   route: '/admin/dashboard1',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Dashboard 2',
  //   iconName: 'solar:chart-line-duotone',
  //   route: '/admin/dashboard2',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Dashboard 3',
  //   iconName: 'solar:screencast-2-line-duotone',
  //   route: '/admin/dashboard3',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Chat',
  //   iconName: 'solar:chat-round-line-line-duotone',
  //   route: 'apps/chat',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Calendar',
  //   iconName: 'solar:calendar-mark-line-duotone',
  //   route: 'apps/calendar',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Email',
  //   iconName: 'solar:letter-line-duotone',
  //   route: 'apps/email/inbox',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Contacts',
  //   iconName: 'solar:phone-line-duotone',
  //   route: 'apps/contacts',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Courses',
  //   iconName: 'solar:book-bookmark-line-duotone',
  //   route: 'apps/courses',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Employee',
  //   iconName: 'solar:user-id-line-duotone',
  //   route: 'apps/employee',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Notes',
  //   iconName: 'solar:document-text-line-duotone',
  //   route: 'apps/notes',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Tickets',
  //   iconName: 'solar:ticket-sale-line-duotone',
  //   route: 'apps/tickets',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Invoice',
  //   iconName: 'solar:bill-list-line-duotone',
  //   route: 'apps/invoice',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'ToDo',
  //   iconName: 'solar:airbuds-case-minimalistic-line-duotone',
  //   route: 'apps/todo',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Taskboard',
  //   iconName: 'solar:clapperboard-edit-line-duotone',
  //   route: 'apps/taskboard',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Roll Base Access',
  //   iconName: 'solar:lock-password-unlocked-line-duotone',
  //   route: 'apps/permission',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Treeview',
  //   iconName: 'solar:bill-line-duotone',
  //   route: 'theme-pages/treeview',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Pricing',
  //   iconName: 'solar:dollar-minimalistic-line-duotone',
  //   route: 'theme-pages/pricing',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Account Setting',
  //   iconName: 'solar:accessibility-line-duotone',
  //   route: 'theme-pages/account-setting',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'FAQ',
  //   iconName: 'solar:question-square-line-duotone',
  //   route: 'theme-pages/faq',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Landingpage',
  //   iconName: 'solar:layers-minimalistic-line-duotone',
  //   route: 'landingpage',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Widgets',
  //   iconName: 'solar:widget-2-line-duotone',
  //   route: 'widgets',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Cards',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'widgets/cards',
  //     },
  //     {
  //       displayName: 'Banners',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'widgets/banners',
  //     },
  //     {
  //       displayName: 'Charts',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'widgets/charts',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Form elements',
  //   iconName: 'solar:password-minimalistic-input-line-duotone',
  //   route: 'forms/forms-elements',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Autocomplete',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'forms/forms-elements/autocomplete',
  //     },
  //     {
  //       displayName: 'Button',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'forms/forms-elements/button',
  //     },
  //     {
  //       displayName: 'Checkbox',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'forms/forms-elements/checkbox',
  //     },
  //     {
  //       displayName: 'Radio',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'forms/forms-elements/radio',
  //     },
  //     {
  //       displayName: 'Datepicker',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'forms/forms-elements/datepicker',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'File Upload',
  //   iconName: 'solar:upload-line-duotone',
  //   route: '/forms/file-upload',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Form Layouts',
  //   iconName: 'solar:file-text-line-duotone',
  //   route: '/forms/form-layouts',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Form Horizontal',
  //   iconName: 'solar:align-horizonta-spacing-line-duotone',
  //   route: '/forms/form-horizontal',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Form Vertical',
  //   iconName: 'solar:align-vertical-spacing-line-duotone',
  //   route: '/forms/form-vertical',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Form Wizard',
  //   iconName: 'solar:archive-minimalistic-line-duotone',
  //   route: '/forms/form-wizard',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Tables',
  //   iconName: 'solar:tablet-line-duotone',
  //   route: 'tables',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Basic Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/basic-table',
  //     },
  //     {
  //       displayName: 'Dynamic Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/dynamic-table',
  //     },
  //     {
  //       displayName: 'Expand Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/expand-table',
  //     },
  //     {
  //       displayName: 'Filterable Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/filterable-table',
  //     },
  //     {
  //       displayName: 'Footer Row Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/footer-row-table',
  //     },
  //     {
  //       displayName: 'HTTP Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/http-table',
  //     },
  //     {
  //       displayName: 'Mix Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/mix-table',
  //     },
  //     {
  //       displayName: 'Multi Header Footer',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/multi-header-footer-table',
  //     },
  //     {
  //       displayName: 'Pagination Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/pagination-table',
  //     },
  //     {
  //       displayName: 'Row Context Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/row-context-table',
  //     },
  //     {
  //       displayName: 'Selection Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/selection-table',
  //     },
  //     {
  //       displayName: 'Sortable Table',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/sortable-table',
  //     },
  //     {
  //       displayName: 'Sticky Column',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/sticky-column-table',
  //     },
  //     {
  //       displayName: 'Sticky Header Footer',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'tables/sticky-header-footer-table',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Data table',
  //   iconName: 'solar:database-line-duotone',
  //   route: '/datatable/kichen-sink',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Line',
  //   iconName: 'solar:align-top-line-duotone',
  //   route: '/charts/line',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Gredient',
  //   iconName: 'solar:bolt-circle-line-duotone',
  //   route: '/charts/gredient',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Area',
  //   iconName: 'solar:chart-square-line-duotone',
  //   route: '/charts/area',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Candlestick',
  //   iconName: 'solar:align-left-line-duotone',
  //   route: '/charts/candlestick',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Column',
  //   iconName: 'solar:chart-2-line-duotone',
  //   route: '/charts/column',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Doughnut & Pie',
  //   iconName: 'solar:pie-chart-2-line-duotone',
  //   route: '/charts/doughnut-pie',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Radialbar & Radar',
  //   iconName: 'solar:align-vertical-center-line-duotone',
  //   route: '/charts/radial-radar',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Ui Components',
  //   iconName: 'solar:share-circle-line-duotone',
  //   route: 'ui-components',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Badge',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/badge',
  //     },
  //     {
  //       displayName: 'Expansion Panel',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/expansion',
  //     },
  //     {
  //       displayName: 'Chips',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/chips',
  //     },
  //     {
  //       displayName: 'Dialog',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/dialog',
  //     },
  //     {
  //       displayName: 'Lists',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/lists',
  //     },
  //     {
  //       displayName: 'Divider',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/divider',
  //     },
  //     {
  //       displayName: 'Menu',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/menu',
  //     },
  //     {
  //       displayName: 'Paginator',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/paginator',
  //     },
  //     {
  //       displayName: 'Progress Bar',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/progress',
  //     },
  //     {
  //       displayName: 'Progress Spinner',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/progress-spinner',
  //     },
  //     {
  //       displayName: 'Ripples',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/ripples',
  //     },
  //     {
  //       displayName: 'Slide Toggle',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/slide-toggle',
  //     },
  //     {
  //       displayName: 'Slider',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/slider',
  //     },
  //     {
  //       displayName: 'Snackbar',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/snackbar',
  //     },
  //     {
  //       displayName: 'Tabs',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/tabs',
  //     },
  //     {
  //       displayName: 'Toolbar',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/toolbar',
  //     },
  //     {
  //       displayName: 'Tooltips',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: 'ui-components/tooltips',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Login',
  //   iconName: 'solar:lock-keyhole-minimalistic-line-duotone',
  //   route: '/auth',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Login 1',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/login',
  //     },
  //     {
  //       displayName: 'Boxed Login',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/boxed-login',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Register',
  //   iconName: 'solar:user-plus-rounded-line-duotone',
  //   route: '/auth',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Side Register',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/side-register',
  //     },
  //     {
  //       displayName: 'Boxed Register',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/boxed-register',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Forgot Password',
  //   iconName: 'solar:password-outline',
  //   route: '/auth',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Side Forgot Password',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/side-forgot-pwd',
  //     },
  //     {
  //       displayName: 'Boxed Forgot Password',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/boxed-forgot-pwd',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Two Steps',
  //   iconName: 'solar:siderbar-line-duotone',
  //   route: '/auth',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Side Two Steps',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/side-two-steps',
  //     },
  //     {
  //       displayName: 'Boxed Two Steps',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/auth/boxed-two-steps',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Error',
  //   iconName: 'solar:bug-minimalistic-line-duotone',
  //   route: '/auth/error',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Maintenance',
  //   iconName: 'solar:settings-line-duotone',
  //   route: '/auth/maintenance',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Menu Level',
  //   iconName: 'solar:align-horizontal-center-line-duotone',
  //   route: '/menu-level',
  //   roles: ['Admin'],
  //   children: [
  //     {
  //       displayName: 'Menu 1',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/menu-1',
  //       children: [
  //         {
  //           displayName: 'Menu 1',
  //           subItemIcon: true,
  //           iconName: 'solar:round-alt-arrow-right-line-duotone',
  //           route: '/menu-1',
  //         },

  //         {
  //           displayName: 'Menu 2',
  //           subItemIcon: true,
  //           iconName: 'solar:round-alt-arrow-right-line-duotone',
  //           route: '/menu-2',
  //         },
  //       ],
  //     },

  //     {
  //       displayName: 'Menu 2',
  //       subItemIcon: true,
  //       iconName: 'solar:round-alt-arrow-right-line-duotone',
  //       route: '/menu-2',
  //     },
  //   ],
  // },
  // {
  //   displayName: 'Disabled',
  //   iconName: 'solar:bookmark-circle-line-duotone',
  //   route: '/disabled',
  //   disabled: true,
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Chip',
  //   iconName: 'solar:branching-paths-up-line-duotone',
  //   route: '/',
  //   chip: true,
  //   chipClass: 'bg-primary text-white',
  //   chipContent: '9',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'Outlined',
  //   iconName: 'solar:add-square-line-duotone',
  //   route: '/',
  //   chip: true,
  //   chipClass: 'b-1 border-primary text-primary',
  //   chipContent: 'outlined',
  //   roles: ['Admin'],
  // },
  // {
  //   displayName: 'External Link',
  //   iconName: 'solar:link-round-angle-bold-duotone',
  //   route: 'https://www.google.com/',
  //   external: true,
  //   roles: ['Admin'],
  // },
];
